// Backend composition root: creates stores/managers and the RPC handler object.

import type { Api, RpcResponse } from '@shared/api';
import { toSqlError } from './errors';
import { fsApi } from './fsApi';
import { platform } from './platform';
import { ConnectionStore } from './store/connections';
import { HistoryStore } from './store/history';
import { getSettings, initSettings, profilesDir, updateSettings } from './store/settings';
import { initSecrets } from './util/secret';
import { TaskManager } from './tasks';
import * as meta from './db/meta';
import { loadTableDesign } from './db/design';
import { applyChanges, countRows, fetchRows } from './db/data';
import { QueryRunner } from './db/exec';
import { SessionManager, type Session } from './db/sessions';
import { createProfilesApi } from './features/profiles';
import { createSnippetsApi } from './features/snippets';
import { createUsersApi } from './features/users';
import { createIoApi } from './features/io';
import { createSyncApi } from './features/sync';
import { createAdminApi } from './features/admin';
import { createBackupApi } from './features/backup';
import { createAutomationApi } from './features/automation';
import { createDataGenApi } from './features/datagen';
import { createModelApi } from './features/model';
import { KS_TUNNEL_PHP } from './httpTunnelScript';

export interface BackendContext {
  connections: ConnectionStore;
  history: HistoryStore;
  sessions: SessionManager;
  tasks: TaskManager;
  runner: QueryRunner;
  /** History logger bound to a session (for SQL generated by the app, e.g. grid edits or DDL) */
  logFor(s: Session): (sql: string, ok: boolean, ms: number, error?: string) => void;
}

export interface Backend {
  api: Api;
  ctx: BackendContext;
  shutdown(): Promise<void>;
}

export function createBackend(): Backend {
  const p = platform();
  initSecrets(p.userDataDir);
  initSettings(p.userDataDir, p.documentsDir);

  const connections = new ConnectionStore(p.userDataDir);
  const history = new HistoryStore(p.userDataDir);
  const sessions = new SessionManager(connections);
  const tasks = new TaskManager();
  const runner = new QueryRunner(sessions, history);
  const logFor =
    (s: Session) =>
    (sql: string, ok: boolean, ms: number, error?: string): void =>
      history.add({
        connectionId: s.connectionId,
        connectionName: s.config.name,
        database: s.database,
        sql,
        durationMs: ms,
        ok,
        error
      });
  const ctx: BackendContext = { connections, history, sessions, tasks, runner, logFor };
  const S = (id: string) => sessions.get(id);

  const api: Api = {
    app: {
      info: async () => ({
        version: p.appVersion,
        platform: process.platform,
        isElectron: p.isElectron,
        electronVersion: p.electronVersion,
        nodeVersion: process.versions.node,
        userDataDir: p.userDataDir,
        documentsDir: p.documentsDir,
        profilesDir: profilesDir()
      }),
      openExternal: (url) => p.openExternal(url),
      showItemInFolder: async (path) => p.showItemInFolder(path),
      quit: async () => p.quit?.(),
      relaunch: async () => p.relaunch?.(),
      tunnelScript: async () => KS_TUNNEL_PHP
    },
    window: {
      minimize: async () => p.window?.minimize(),
      toggleMaximize: async () => p.window?.toggleMaximize() ?? false,
      close: async () => p.window?.close(),
      isMaximized: async () => p.window?.isMaximized() ?? false,
      setTitleBarColors: async (bg, fg) => p.window?.setTitleBarColors(bg, fg),
      toggleDevTools: async () => p.window?.toggleDevTools(),
      reload: async () => p.window?.reload(),
      editCommand: async (cmd) => {
        if (!p.window) return false;
        p.window.editCommand(cmd);
        return true;
      }
    },
    dialog: {
      openFile: async (o) => (p.openFileDialog ? p.openFileDialog(o) : null),
      saveFile: async (o) => (p.saveFileDialog ? p.saveFileDialog(o) : null),
      openDirectory: async (o) => (p.openDirectoryDialog ? p.openDirectoryDialog(o) : null)
    },
    fs: fsApi,
    settings: {
      get: async () => getSettings(),
      update: (patch) => updateSettings(patch)
    },
    connections: {
      list: async () => connections.list(),
      save: async (c) => {
        sessions.forgetCredentials(c.id);
        return connections.save(c);
      },
      remove: async (id) => {
        await sessions.closeConnection(id);
        await connections.remove(id);
      },
      reorder: (ids) => connections.reorder(ids),
      saveGroup: (g) => connections.saveGroup(g),
      removeGroup: (id) => connections.removeGroup(id),
      test: (c) => sessions.test(c),
      listDatabases: (c) => sessions.listDatabases(c),
      exportFile: (file, ids, passphrase) => connections.exportFile(file, ids, passphrase),
      importFile: (file, passphrase) => connections.importFile(file, passphrase)
    },
    session: {
      open: async (cid, db, creds) => (await sessions.open(cid, db, creds)).info(),
      close: (id) => sessions.close(id),
      closeConnection: (cid) => sessions.closeConnection(cid),
      useDatabase: (id, db) => S(id).useDatabase(db),
      ping: async (id) => {
        const t0 = Date.now();
        await S(id).conn.ping();
        return Date.now() - t0;
      },
      info: async (id) => S(id).info()
    },
    meta: {
      databases: (id) => meta.databases(S(id)),
      tables: (id, schema) => meta.tables(S(id), schema),
      views: (id, schema) => meta.views(S(id), schema),
      routines: (id, schema) => meta.routines(S(id), schema),
      events: (id, schema) => meta.events(S(id), schema),
      triggers: (id, schema, table) => meta.triggers(S(id), schema, table),
      columns: (id, schema, table) => meta.columns(S(id), schema, table),
      ddl: (id, schema, kind, name) => meta.ddl(S(id), schema, kind, name),
      charsets: (id) => meta.charsets(S(id)),
      collations: (id) => meta.collations(S(id)),
      engines: (id) => meta.engines(S(id)),
      tableDesign: (id, schema, table) => loadTableDesign(S(id), schema, table),
      completion: (id, schema) => meta.completion(S(id), schema)
    },
    query: {
      execute: (id, sql, opts) => runner.execute(id, sql, opts),
      cancel: (id) => runner.cancel(id)
    },
    data: {
      fetch: (id, req) => fetchRows(S(id), req),
      count: (id, schema, table, where) => countRows(S(id), schema, table, where),
      apply: (id, req) => applyChanges(S(id), req, logFor(S(id)))
    },
    history: {
      list: async (f) => history.list(f),
      clear: async () => history.clear()
    },
    tasks: {
      list: async () => tasks.list(),
      log: async (id) => tasks.log(id),
      cancel: async (id) => tasks.cancel(id)
    },
    profiles: createProfilesApi(),
    snippets: createSnippetsApi(p.userDataDir),
    users: createUsersApi(ctx),
    io: createIoApi(ctx),
    sync: createSyncApi(ctx),
    admin: createAdminApi(ctx),
    backup: createBackupApi(ctx),
    automation: createAutomationApi(ctx),
    datagen: createDataGenApi(ctx),
    model: createModelApi(ctx)
  };

  return { api, ctx, shutdown: () => sessions.closeAll() };
}

export async function dispatch(api: Api, method: string, args: unknown[]): Promise<RpcResponse> {
  const [ns, fn] = method.split('.');
  const target = (api as unknown as Record<string, Record<string, unknown>>)[ns]?.[fn];
  if (typeof target !== 'function') return { ok: false, error: { message: `Unknown method: ${method}` } };
  try {
    const value = await (target as (...a: unknown[]) => Promise<unknown>)(...(args ?? []));
    return { ok: true, value };
  } catch (e) {
    const err = toSqlError(e);
    return { ok: false, error: { ...err, name: e instanceof Error ? e.name : undefined } };
  }
}
