// MySQL keywords, functions and data types for completion / highlighting.

export const MYSQL_KEYWORDS: string[] = (
  'ACCESSIBLE ACTION ADD AFTER AGAINST ALGORITHM ALL ALTER ANALYZE AND ANY AS ASC ASCII AT AUTO_INCREMENT AVG_ROW_LENGTH ' +
  'BEFORE BEGIN BETWEEN BINARY BOTH BTREE BY CALL CASCADE CASCADED CASE CHANGE CHARACTER CHARSET CHECK CHECKSUM CLOSE COLLATE ' +
  'COLUMN COLUMNS COMMENT COMMIT COMMITTED COMPACT COMPRESSED COMPRESSION CONDITION CONSISTENT CONSTRAINT CONTINUE CONVERT ' +
  'CREATE CROSS CUBE CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATA DATABASE DATABASES DAY ' +
  'DAY_HOUR DAY_MINUTE DAY_SECOND DEALLOCATE DECLARE DEFAULT DEFINER DELAYED DELAY_KEY_WRITE DELETE DESC DESCRIBE DETERMINISTIC ' +
  'DISABLE DISCARD DISTINCT DISTINCTROW DIV DO DROP DUAL DUPLICATE DYNAMIC EACH ELSE ELSEIF ENABLE ENCLOSED END ENDS ENGINE ENGINES ' +
  'ENFORCED ESCAPE ESCAPED EVENT EVENTS EVERY EXCEPT EXECUTE EXISTS EXIT EXPLAIN EXTENDED FALSE FETCH FIELDS FIRST FIXED FLUSH ' +
  'FOLLOWING FOLLOWS FOR FORCE FOREIGN FORMAT FROM FULL FULLTEXT FUNCTION GENERATED GLOBAL GRANT GRANTS GROUP GROUPING HANDLER ' +
  'HASH HAVING HELP HIGH_PRIORITY HOST HOSTS HOUR IDENTIFIED IF IGNORE IMPORT IN INDEX INDEXES INFILE INNER INOUT INSERT ' +
  'INSTALL INTERVAL INTO INVISIBLE INVOKER IS ISOLATION ITERATE JOIN KEY KEYS KEY_BLOCK_SIZE KILL LAST LATERAL LEADING LEAVE ' +
  'LEFT LESS LEVEL LIKE LIMIT LINEAR LINES LOAD LOCAL LOCK LOCKED LOGS LOOP LOW_PRIORITY MASTER MATCH MAXVALUE MAX_ROWS MERGE ' +
  'MINUTE MIN_ROWS MODE MODIFIES MODIFY MONTH NAMES NATURAL NEXT NO NONE NOT NOWAIT NO_WRITE_TO_BINLOG NULL NULLS OF OFFSET ON ' +
  'ONLY OPEN OPTIMIZE OPTION OPTIONALLY OR ORDER OUT OUTER OUTFILE OVER OWNER PACK_KEYS PARSER PARTITION PARTITIONING ' +
  'PARTITIONS PASSWORD PERSIST PERSIST_ONLY PLUGINS PRECEDES PRECEDING PREPARE PRESERVE PREV PRIMARY PRIVILEGES PROCEDURE ' +
  'PROCESSLIST PROFILE PROFILES PURGE QUARTER QUICK RANGE READ READS RECURSIVE REDUNDANT REFERENCES REGEXP RELEASE RELOAD ' +
  'REMOVE RENAME REORGANIZE REPAIR REPEAT REPEATABLE REPLACE REQUIRE RESET RESIGNAL RESTRICT RETURN RETURNS REVOKE RIGHT RLIKE ' +
  'ROLE ROLLBACK ROLLUP ROUTINE ROW ROWS ROW_FORMAT SAVEPOINT SCHEDULE SCHEMA SCHEMAS SECOND SECURITY SELECT SEPARATOR ' +
  'SERIALIZABLE SESSION SET SHARE SHOW SHUTDOWN SIGNAL SIGNED SKIP SLAVE SNAPSHOT SOME SOUNDS SPATIAL SQL SQLEXCEPTION ' +
  'SQLSTATE SQLWARNING SQL_BIG_RESULT SQL_BUFFER_RESULT SQL_CALC_FOUND_ROWS SQL_NO_CACHE SQL_SMALL_RESULT SRID START STARTING ' +
  'STARTS STATS_AUTO_RECALC STATS_PERSISTENT STATS_SAMPLE_PAGES STATUS STORAGE STORED STRAIGHT_JOIN SUBPARTITION SYSTEM TABLE ' +
  'TABLES TABLESPACE TEMPORARY TEMPTABLE TERMINATED THAN THEN TO TRAILING TRANSACTION TRIGGER TRIGGERS TRUE TRUNCATE TYPE ' +
  'UNBOUNDED UNCOMMITTED UNDEFINED UNDO UNION UNIQUE UNKNOWN UNLOCK UNSIGNED UNTIL UPDATE USAGE USE USER USING VALUE VALUES ' +
  'VARIABLES VIEW VIRTUAL VISIBLE WARNINGS WEEK WHEN WHERE WHILE WINDOW WITH WORK WRITE XA XOR YEAR YEAR_MONTH ZEROFILL'
).split(' ');

export const MYSQL_FUNCTIONS: string[] = (
  'ABS ACOS ADDDATE ADDTIME AES_DECRYPT AES_ENCRYPT ANY_VALUE ASCII ASIN ATAN ATAN2 AVG BENCHMARK BIN BIN_TO_UUID BIT_AND ' +
  'BIT_COUNT BIT_LENGTH BIT_OR BIT_XOR CAST CEIL CEILING CHAR CHAR_LENGTH CHARACTER_LENGTH CHARSET COALESCE COERCIBILITY ' +
  'COLLATION COMPRESS CONCAT CONCAT_WS CONNECTION_ID CONV CONVERT CONVERT_TZ COS COT COUNT CRC32 CUME_DIST CURDATE ' +
  'CURRENT_ROLE CURTIME DATABASE DATE DATE_ADD DATE_FORMAT DATE_SUB DATEDIFF DAY DAYNAME DAYOFMONTH DAYOFWEEK DAYOFYEAR ' +
  'DEGREES DENSE_RANK ELT EXP EXPORT_SET EXTRACT EXTRACTVALUE FIELD FIND_IN_SET FIRST_VALUE FLOOR FORMAT FORMAT_BYTES ' +
  'FOUND_ROWS FROM_BASE64 FROM_DAYS FROM_UNIXTIME GET_FORMAT GET_LOCK GREATEST GROUP_CONCAT HEX HOUR IF IFNULL INET_ATON ' +
  'INET_NTOA INET6_ATON INET6_NTOA INSERT INSTR IS_FREE_LOCK IS_IPV4 IS_IPV6 IS_USED_LOCK IS_UUID ISNULL JSON_ARRAY ' +
  'JSON_ARRAYAGG JSON_ARRAY_APPEND JSON_ARRAY_INSERT JSON_CONTAINS JSON_CONTAINS_PATH JSON_DEPTH JSON_EXTRACT JSON_INSERT ' +
  'JSON_KEYS JSON_LENGTH JSON_MERGE_PATCH JSON_MERGE_PRESERVE JSON_OBJECT JSON_OBJECTAGG JSON_OVERLAPS JSON_PRETTY JSON_QUOTE ' +
  'JSON_REMOVE JSON_REPLACE JSON_SCHEMA_VALID JSON_SEARCH JSON_SET JSON_STORAGE_SIZE JSON_TABLE JSON_TYPE JSON_UNQUOTE ' +
  'JSON_VALID JSON_VALUE LAG LAST_DAY LAST_INSERT_ID LAST_VALUE LCASE LEAD LEAST LEFT LENGTH LN LOAD_FILE LOCALTIME LOCATE ' +
  'LOG LOG10 LOG2 LOWER LPAD LTRIM MAKE_SET MAKEDATE MAKETIME MAX MD5 MICROSECOND MID MIN MINUTE MOD MONTH MONTHNAME NOW ' +
  'NTH_VALUE NTILE NULLIF OCT OCTET_LENGTH ORD PERCENT_RANK PERIOD_ADD PERIOD_DIFF PI POSITION POW POWER QUARTER QUOTE ' +
  'RADIANS RAND RANDOM_BYTES RANK REGEXP_INSTR REGEXP_LIKE REGEXP_REPLACE REGEXP_SUBSTR RELEASE_ALL_LOCKS RELEASE_LOCK REPEAT ' +
  'REPLACE REVERSE RIGHT ROUND ROW_COUNT ROW_NUMBER RPAD RTRIM SCHEMA SEC_TO_TIME SECOND SESSION_USER SHA1 SHA2 SIGN SIN ' +
  'SLEEP SOUNDEX SPACE SQRT ST_AREA ST_ASTEXT ST_ASWKT ST_BUFFER ST_CONTAINS ST_DISTANCE ST_DISTANCE_SPHERE ST_GEOMFROMTEXT ' +
  'ST_INTERSECTS ST_LATITUDE ST_LONGITUDE ST_POINTFROMTEXT ST_SRID ST_WITHIN ST_X ST_Y STD STDDEV STDDEV_POP STDDEV_SAMP ' +
  'STR_TO_DATE STRCMP SUBDATE SUBSTR SUBSTRING SUBSTRING_INDEX SUBTIME SUM SYSDATE SYSTEM_USER TAN TIME TIME_FORMAT ' +
  'TIME_TO_SEC TIMEDIFF TIMESTAMP TIMESTAMPADD TIMESTAMPDIFF TO_BASE64 TO_DAYS TO_SECONDS TRIM TRUNCATE UCASE UNCOMPRESS ' +
  'UNHEX UNIX_TIMESTAMP UPPER USER UTC_DATE UTC_TIME UTC_TIMESTAMP UUID UUID_SHORT UUID_TO_BIN VALUES VAR_POP VAR_SAMP ' +
  'VARIANCE VERSION WEEK WEEKDAY WEEKOFYEAR WEIGHT_STRING YEAR YEARWEEK'
).split(' ');

export const MYSQL_TYPES: string[] = (
  'TINYINT SMALLINT MEDIUMINT INT INTEGER BIGINT DECIMAL NUMERIC FLOAT DOUBLE REAL BIT BOOL BOOLEAN SERIAL DATE DATETIME ' +
  'TIMESTAMP TIME YEAR CHAR VARCHAR BINARY VARBINARY TINYTEXT TEXT MEDIUMTEXT LONGTEXT TINYBLOB BLOB MEDIUMBLOB LONGBLOB ENUM ' +
  'SET JSON GEOMETRY POINT LINESTRING POLYGON MULTIPOINT MULTILINESTRING MULTIPOLYGON GEOMETRYCOLLECTION'
).split(' ');

/** Words after which the next identifier is not a table alias */
export const NON_ALIAS_WORDS = new Set(
  'WHERE JOIN ON LEFT RIGHT INNER OUTER CROSS NATURAL STRAIGHT_JOIN GROUP ORDER LIMIT SET USING UNION HAVING WINDOW FOR LOCK VALUES SELECT PARTITION USE FORCE IGNORE INTO AS'.split(
    ' '
  )
);
